name: NPM Preview
on: 
  push:
    paths: 
      - packages/emailthing/**
      - apps/cli/**
      - .github/workflows/npm-preview.yml
    branches: main
  pull_request:
    paths: 
      - packages/emailthing/**
      - apps/cli/**
      - .github/workflows/npm-preview.yml
    branches: main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        include:
          - dir: packages/emailthing
            name: emailthing
          - dir: apps/cli
            name: "@emailthing/cli"
    name: Build ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile

      - run: bun run build && bunx pkg-pr-new publish --comment=off
        working-directory: ${{ matrix.dir }}
